/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { InitDiamond } from "../InitDiamond";

export class InitDiamond__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<InitDiamond> {
    return super.deploy(overrides || {}) as Promise<InitDiamond>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): InitDiamond {
    return super.attach(address) as InitDiamond;
  }
  connect(signer: Signer): InitDiamond__factory {
    return super.connect(signer) as InitDiamond__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): InitDiamond {
    return new Contract(address, _abi, signerOrProvider) as InitDiamond;
  }
}

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "recipient",
            type: "address",
          },
          {
            internalType: "address",
            name: "poolInput",
            type: "address",
          },
          {
            internalType: "address",
            name: "poolOutput",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amount0Out",
            type: "uint256",
          },
        ],
        internalType: "struct InitDiamond.Args",
        name: "_args",
        type: "tuple",
      },
    ],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610239806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80631196fa2214610030575b600080fd5b61016161003e36600461017f565b7fc8fcad8db84d3cc18b4c41d551ea0ee66dd599cde068d998e57d5e09332c131f60209081527f699d9daa71b280d05a152715774afa0a81a312594b2d731d6b0b2552b7d6f69f8054600160ff1991821681179092557ff97e938d8af42f52387bb74b8b526fda8f184cc2aa534340a8d75a88fbecc77580548216831790557f65d510a5d8f7ef134ec444f7f34ee808c8eeb5177cdfd16be0c40fe1ab43369580548216831790556307f5828d60e41b6000527f5622121b47b8cd0120c4efe45dd5483242f54a3d49bd7679be565d47694918c3805490911682179055825181546001600160a01b03199081166001600160a01b039283161790925591830151600280548316918416919091179055604090920151600380549093169116179055565b005b80356001600160a01b038116811461017a57600080fd5b919050565b600060808284031215610190578081fd5b6040516080810181811067ffffffffffffffff821117156101bf57634e487b7160e01b83526041600452602483fd5b6040526101cb83610163565b81526101d960208401610163565b60208201526101ea60408401610163565b604082015260608301356060820152809150509291505056fea26469706673582212200575c211cd71f56426f858d70e165ad4e7fe2ac698ba66ad670e7a145d28e22164736f6c63430008020033";
